FsJuniorTestTask.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using FsJuniorTestTask.Bll.User;
using FsJuniorTestTask.Core.Dto;
using FsJuniorTestTask.Web.Models.Account;

namespace FsJuniorTestTask.Web.Controllers
{
    public class UserController : Controller
    {
        #region Fields

        private readonly IUserService _userService;

        #endregion

        #region Constructor

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        #endregion

        #region Methods

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var userResult = await _userService.FindUser(model.Email);
                if (!userResult.Success)
                {
                    ModelState.AddModelError("", userResult.Error.Message);
                }
                else
                {
                    if (userResult.Value == null)
                    {
                        var createResult = await _userService.CreateUser(
                            new UserDto
                            {
                                Name = model.Name,
                                Email = model.Email,
                                Password = model.Password
                            });

                        if (!createResult.Success)
                        {
                            ModelState.AddModelError("", userResult.Error.Message);
                        }
                        else
                        {
                            return RedirectToAction("List", "Film");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Ошибка регистрации пользователя");
                    }
                }
            }

            return View(model);
        }
    }

    #endregion
}

FsJuniorTestTask.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FsJuniorTestTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Film" asp-action="List">FsJuniorTestTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Регистрация</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - FsJuniorTestTask
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>